### ISSUE TITLE
MultipartFile只支持post方法，不能使用put方法上传文件

### ISSUE THREAD

**Issue by raomuyang** [raomuyang/ERP-Notebook#10]
如题，所以原本以rest规范设计的“创建文件使用put方法“需要暂时改成POST方法

> The multipart support as used by Spring doesn't support other request method then POST. For the StandardServletMultipartResolver this is hardcoded in that class.

For the CommonsMultipartResolver it is hardcoded in the ServletFileUpload utility class from the Apache Commons Fileupload project.

Tthe Form-based File Upload in HTML (RFC1867) isn't really explicit about this but the only mention of a used HTTP method is POST.

In short, at the moment only POST is supported by the frameworks you might be able to work around it by reimplemening some classes but if it works (especially with the default Servlet 3.0 file upload support) might depend on your containe

**Comment by raomengnan** [comment]
以POST方式上传图片并不一定违反了最初“PUT创建资源”的规范，因为图片所对应的资源已经存在，而新上传的图片只是对旧有资源的更新
